name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**/*'
    tags-ignore:
      - '**/*'
    tags-ignore:
      - '**/*'
jobs:
  build:
    if: |
      github.event_name == 'pull_request' && github.base_ref == 'main' || 
      contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/guestbook-go:latest
